### ISSUE TITLE
Command \textomega unavailable in encoding T1

### ISSUE THREAD

**Issue by Biltu** [ulyngs/oxforddown#1]
Hello, 
Rmarkdown is not printing $\omega$, $\Delta$ or $\Psi$. The error message is- 

! LaTeX Error: Command \textomega unavailable in encoding T1.

Is there a solution for that?

Thanking you,
Mohammad Tanbir Habib

**Comment by ulyngs** [comment]
Could you download the latest version of the repository, then try again?
