### ISSUE TITLE
`hidelink: false` does not unhide links

### ISSUE THREAD

**Issue by shirdekel** [ulyngs/oxforddown#18]
Currently, `index.Rmd` has

```yml
hidelinks: true # false to highlight clickable links with a colored border
```

However, changing this to `false` does not add the border. I think that this is because `hyperref`'s `hidelinks` option is not a boolean, but it is its presence that turns on the link hiding (see page 10 of the [manual](http://mirrors.ctan.org/macros/latex/contrib/hyperref/doc/hyperref-doc.pdf)). Manually removing this option from `template.tex` re-enables the default borders.

**Comment by ulyngs** [comment]
thanks for catching this!

I just fixed it in [this commit](https://github.com/ulyngs/oxforddown/commit/d397b0e3b2215b37e3eb9b0339ef0013c4cdd677)
