### ISSUE TITLE
Make page number, not text, be link in TOC

### ISSUE THREAD

**Issue by shirdekel** [ulyngs/oxforddown#26]
Next to the `linkcolor-rgb` value in `index.Rmd` there is a comment that says that "In the coloring normal links looks a bit excessive, as it highlights also all links in the table of contents"

Adding `linktocpage` to `hypersetup` makes the links appear only for the page numbers, not the text, in the TOC. This makes the amount of link highlighting a little less excessive.

For instance:

```latex
\hypersetup{
  hidelinks,
  colorlinks,
  linktocpage,
  linkcolor=$if(linkcolor-rgb)$mylinkcolor$else$.$endif$,
  urlcolor=$if(urlcolor-rgb)$myurlcolor$else$.$endif$,
  citecolor=$if(citecolor-rgb)$mycitecolor$else$.$endif$
}
```

Obviously this could be made optional and be controlled from `index.Rmd`. Happy to submit a PR.

**Comment by ulyngs** [comment]
Agreed - I was thinking a bit about this when I was looking into the different ways to allow for customisation of link colouring etc.

Could you submit a PR and also add a suggested section that documents this to the new 'How to Use' chapter?

**Comment by shirdekel** [comment]
Just submitted the PR. Can you clarify what you expect for the 'How to Use' chapter, though? Currently it seems quite high level and it feels like adding something about TOC link highlighting would be out of place. Or do you eventually want to it be quite detailed?

**Comment by ulyngs** [comment]
Good question, I was wondering a bit about what would be best.

There's a couple of options:

1. the 'How to Use' chapter remains high-level, and the more detailed things such as TOC link highlighting go in the 'Customisations and Extensions chapter'
2. the 'How to Use' chapter adds a section named something like 'setting layout options in index.Rmd' - this section has brief explanations for each of the setting that are available directly from **index.Rmd**'s YAML header, without any further tweaking

I favour the second option - would you agree?

**Comment by ulyngs** [comment]
Merged pull request and [tweaked](https://github.com/ulyngs/oxforddown/commit/b5a81f2f332ec7a0d9896778ee469781894d7681)

**Comment by Zenahr** [comment]
@ulyngs since this has been merged the issue can be closed.

**Comment by shirdekel** [comment]
> Good question, I was wondering a bit about what would be best.
> 
> There's a couple of options:
> 
>     1. the 'How to Use' chapter remains high-level, and more detailed things such as TOC link highlighting go in the 'Customisations and Extensions chapter'
> 
>     2. the 'How to Use' chapter adds a section named something like 'setting layout options in index.Rmd' - this section has brief explanations for each of the setting that are available directly from **index.Rmd**'s YAML header, without any further tweaking
> 
> 
> I favour the second option - would you agree?

Sorry for the delayed response. Yes, I thought that something like option 2 is better!
