### ISSUE TITLE
`lineno` seems to screw up encoding

### ISSUE THREAD

**Issue by shirdekel** [ulyngs/oxforddown#29]
When I turn on line numbers my PDF document becomes unsearchable, and copy-pasting text leads to weird characters. Visually, however, it looks perfectly fine.

When I have some more time I'll come back and provide a reprex, but I just wanted to note this for now in case someone else has this issue. (Also, it doesn't look like `lineno` has active support when I follow the link in CTAN: http://www.webdesign-bu.de/uwe_lueck/contact.html.)

**Comment by ulyngs** [comment]
That sounds odd. 

I had a quick look and was unable to reproduce your problem, however - my PDF still seems to be searchable with line numbers turned on?

<img width="734" alt="image" src="https://user-images.githubusercontent.com/23137032/129329711-e3db4753-fa8c-4f35-bcc9-bda1558f8f40.png">

Copy-pasting from the PDF and into sublime also seems to work fine me?

**Comment by shirdekel** [comment]
Hey @ulyngs, sorry for taking so long to respond to this. (I just defended my thesis today so have a bit more time to tie up loose ends.)

I worked out the issue; it was indeed nothing to with `lineno`. It was using the signature inserting function in Mac's Preview app! Before submitting I added both line numbers and the signature, so confounded the two.
