### ISSUE TITLE
Some characters appear incorrectly when using xelatex or lualatex

### ISSUE THREAD

**Issue by matthew-law** [ulyngs/oxforddown#32]
Disclaimer that this issue might not be entirely one of oxforddown but it goes away when I don't specify `template: templates/brief_template.tex`, so I assume it's caused by something within that template.

When I use the characters ¹ / ² / ³ with the xelatex or lualatex engines, they get rendered as ź / š / ş in the pdf output.

### How to reproduce:
I knit a .Rmd with the following YAML:
```
---
title: "superscript reprex"
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    latex_engine: pdflatex (or lualatex/xelatex)
---
```

and the following content:

```
unicode superscript:

1: ¹

2: ²

3: ³
```

### Results
output when `latex_engine: pdflatex`:
![image](https://user-images.githubusercontent.com/18603830/132925571-102f6ef7-52b3-4113-9bab-1d69b1696b45.png)

output when `latex_engine: lualatex`:
![image](https://user-images.githubusercontent.com/18603830/132925513-c073d002-c4b3-40d3-85b4-aa5c540c63fe.png)

output when `latex_engine: xelatex`:
![image](https://user-images.githubusercontent.com/18603830/132925490-fbb5ad61-0c3c-4081-9ec1-54d6baf14136.png)

While this reprex uses the brief_template.tex template, it also occurs when I knit a whole thesis using the main template. It also occurs when I swap out the font for another one, so I don't think that's the issue (and in any case `pdflatex` does show the correct characters, so they're definitely there).

As a side note, I do know how to use normal superscript in markdown and have been usually using that, but haven't found a way to do so with` kableExtra::add_header_above()`, hence the use of the ² character as a workaround – if anyone reading this does know how to do this do let me know! Or if there is any other workaround that will allow me to use ² with lualatex or xelatex (pdflatex gives me other unrelated errors), that would be greatly appreciated!

**Comment by ulyngs** [comment]
So it seems that the problem to solve then is how to get superscript with `kableExtra::add_header_above()`.

For superscript, the solution is simply to use the normal markdown notation for superscript (`^1^`) which gives the right output with both pdflatex and xelatex.

Can you provide a reprex of the problem with `kableExtra::add_header_above()` and superscript?

**Comment by matthew-law** [comment]
Here's an example with `latex_engine: pdflatex` (so it does work as intended):

```r
islands[1:10] %>% 
  kable() %>% 
  add_header_above(c("", "Area (miles²)"))
```
![image](https://user-images.githubusercontent.com/18603830/133880556-63601406-32ad-433e-bbfd-04435ba748c5.png)

and here's the same thing when `latex_engine: lualatex` or `latex_engine: xelatex`:
![image](https://user-images.githubusercontent.com/18603830/133880585-5375d178-9b2e-4ee0-be36-45ab82cff6b0.png)

Here are some of the approaches I've tried to circumvent the issue and their outputs (which are the same irrespective of `latex_engine` used) – some of these were long shots I didn't really expect to work but thought it was worth testing just in case:

```r
islands[1:10] %>% 
  kable() %>% 
  add_header_above(c("", "Area (miles^2^)"))
```
![image](https://user-images.githubusercontent.com/18603830/133880685-0d108706-42d9-45be-a8cd-23abf6a060d4.png)

```r
islands[1:10] %>% 
  kable() %>% 
  add_header_above(c("", "Area (miles<sup>2</sup>)"))
```

![image](https://user-images.githubusercontent.com/18603830/133880713-86057d2a-0acd-405d-a980-18cecfaed62b.png)

```r
islands[1:10] %>%
  kable() %>%
  add_header_above(c("", expression("Area (miles"^2*")")))
```
fails to knit with the error
`Error in as.data.frame.default(x[[i]], optional = TRUE) : cannot coerce class ‘"expression"’ to a data.frame`

**Comment by ulyngs** [comment]
You just need to insert it using the latex syntax:

```r
islands[1:10] %>% 
  kable() %>% 
  add_header_above(c("", "Area (miles\\\\textsuperscript{2})"), escape=FALSE)
```

<img width="236" alt="image" src="https://user-images.githubusercontent.com/23137032/133881348-75bb66ac-ed65-408b-8159-0a61ffb5668b.png">

**Comment by matthew-law** [comment]
Is there a way to do this which will work for both the latex and html outputs, or some way to specify different chunks to run for each?

**Comment by ulyngs** [comment]
Sure, just do something like

```r
if (knitr::is_latex_output()) {
  islands[1:10] %>% 
    kable() %>% 
    add_header_above(c("", "Area (miles\\\\textsuperscript{2})"), escape=FALSE)
} else if (knitr::is_html_output()){
  islands[1:10] %>% 
    kable() %>% 
    add_header_above(c("", "Area (miles^2^"))
}
```

**Comment by matthew-law** [comment]
Perfect, thanks!
