### ISSUE TITLE
Changing the title size of the thesis

### ISSUE THREAD

**Issue by zavud** [ulyngs/oxforddown#34]
Is there a way to decrease the title size? My current title size is so big that there are 2 title pages whereas I want to have only 1 title page where everything is included.

**Comment by ulyngs** [comment]
Just added the ability to set this from **index.Rmd** in the latest commit (bda78c1)

### title page
...
 gap-before-crest: 25mm
 gap-after-crest: 25mm

**Comment by zavud** [comment]
This very nicely solves the problem. Thanks a lot! :)
