### ISSUE TITLE
One side document class within a doubleside one

### ISSUE THREAD

**Issue by JoseBSL** [ulyngs/oxforddown#36]
I have prepared the thesis with alternate headers with fancyhdr and I'm very happy with the output. However, the sections before the chapters I would like them with a single side page.

I have set twoside ``\documentclass[a4paper, twoside,$if(page-layout)$$page-layout$$endif$]{templates/ociamthesis}
`` but I want to have single side pages on the declaration, acknowledgements, etc...

I ilustrate it here the issue. I'm trying to avoid this white page.

<img width="239" alt="Screen Shot 2021-11-08 at 10 36 57 am" src="https://user-images.githubusercontent.com/19801021/140718546-04ec1baa-072f-45a5-981c-8e1ca735f658.png">

I've seen that switching between ``\setboolean{@twoside}{false}`` and ``\setboolean{@twoside}{true}``, using ``\cleardoublepage`` or ``\newgeometry`` could be possible solutions but I haven't been able to change it.
 Any advice with this?

**Comment by JoseBSL** [comment]
I haven't found a solution but I think is also nice as it is!

**Comment by ulyngs** [comment]
The silly-but-works solution of course is to just open the PDF in a PDF reader and then delete the unwanted blank page. ;)

On Mac you can do this by opening the PDF in Preview, then showing the Thumbnails sidebar, then click the page you want to delete, and press the backspace key to delete it.
