### ISSUE TITLE
! LaTeX Error: This NFSS system isn't set up properly.

### ISSUE THREAD

**Issue by kanazawahere** [ulyngs/oxforddown#4]
! LaTeX Error: This NFSS system isn't set up properly.

Error: Failed to compile _main.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See _main.log for more info.
In addition: Warning messages:
1: In parse_packages(logfile, quiet = c(TRUE, FALSE, FALSE)) :
  Failed to find a package that contains authoryear.dbx
2: In parse_packages(logfile, quiet = c(TRUE, FALSE, FALSE)) :
  Failed to find a package that contains biblatex-dm.cfg
3: In parse_packages(logfile, quiet = c(TRUE, FALSE, FALSE)) :
  Failed to find a package that contains latin.lbx
Execution halted
make: *** [pdf] Error 1

R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] tinytex_0.13

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0    xfun_0.7       packrat_0.5.0

**Comment by ulyngs** [comment]
What latex installation are you using? Try getting a full installation of latex (https://www.latex-project.org/get/) rather than tinytex and see if that fixes it!

**Comment by ilsePit** [comment]
I had the same issue. I am using tinytex in Rstudio on Ubuntu 18.04. I solved the issue by installing the package 'cbfonts-fd', which includes the file 'LGRcmr.fd' that was missing according to _main.log.

tinytex::tlmgr_install('cbfonts-fd')

Hopefully that resolves the issue of not being able to use tinytex!

**Comment by ulyngs** [comment]
That's brilliant, thanks for figuring this out Ilse! I will make a note of this in the readme!

**Comment by ilsePit** [comment]
I'm wondering if adding `\usepackage{cbfonts-fd}` to the latex file will also do the trick.. Have not tried this out yet (and not that literate in latex) but was planning to try that soon.

**Comment by bttomio** [comment]
> I had the same issue. I am using tinytex in Rstudio on Ubuntu 18.04. I solved the issue by installing the package 'cbfonts-fd', which includes the file 'LGRcmr.fd' that was missing according to _main.log.
> 
> tinytex::tlmgr_install('cbfonts-fd')
> 
> Hopefully that resolves the issue of not being able to use tinytex!

Thank you very much! It solved the same issue on Ubuntu 20.04.2 LTS.

**Comment by shirdekel** [comment]
Had the same error with Mac 10.14.6 (18G6032) using `tinytex`.

`tinytex::tlmgr_install('cbfonts-fd')` fixed it.

**Comment by flashshare** [comment]
> I had the same issue. I am using tinytex in Rstudio on Ubuntu 18.04. I solved the issue by installing the package 'cbfonts-fd', which includes the file 'LGRcmr.fd' that was missing according to _main.log.
> 
> tinytex::tlmgr_install('cbfonts-fd')
> 
> Hopefully that resolves the issue of not being able to use tinytex!

Thanks. It works for me also.

**Comment by yihui** [comment]
I'll truly appreciate it if someone could report this type of issue to the [**tinytex** repo](https://github.com/yihui/tinytex) in the future. I had no idea that many people were suffering from this issue until I saw @bttomio's [tweet today](https://twitter.com/bttomio/status/1384975670665695236). It is actually fairly simple to fix in **tinytex**, and I just did it. You can install the development version via

```r
remotes::install_github('yihui/tinytex')
```

You all may be too kind fo bother me, which I also appreciate very much. I am often busy indeed, but that's exactly why I love investing 10 minutes on my side to fix a small issue to save hours of other people's time! :)

**Comment by Pawanbhatt500** [comment]
I am having the same problem. Please help me !!
I am using texlive and texstudio on Ububtu 21.03

The error is
![image](https://user-images.githubusercontent.com/125285629/218490447-e783f234-2930-4e1c-bfc4-92cdb3e6659b.png)

**Comment by alita-moore** [comment]
I had the same problem, possibly the problem is the order in which you're importing packages or conflicting packages. For example:
```
\usepackage{fontspec}
\usepackage{boisik}
\usepackage[OT1]{fontenc}
```

gives the following errror
```
No file LBMlmr.fd.

/tmp/tmpqxhbk5l7.tex:63: LaTeX Error: This NFSS system isn't set up properly.
```

But 
```latex
\usepackage{fontspec}
\usepackage[OT1]{fontenc}
\usepackage{boisik}
```

compiles without errors. Also, fonts with math support may be conflicting with the unicode-math package so you should try removing the unicode-math package.

**Comment by sht** [comment]
> I had the same issue. I am using tinytex in Rstudio on Ubuntu 18.04. I solved the issue by installing the package 'cbfonts-fd', which includes the file 'LGRcmr.fd' that was missing according to _main.log.
> 
> tinytex::tlmgr_install('cbfonts-fd')
> 
> Hopefully that resolves the issue of not being able to use tinytex!

Awesome, thanks for the solution. I saved me a lot of time of debugging!
