### ISSUE TITLE
Adding Acknowledgements and Abstract to table of contents with visible roman page numbering 

### ISSUE THREAD

**Issue by keanarichards** [ulyngs/oxforddown#41]
Hello, 

Any recommendations on how to edit what is included in the table of contents? For instance, my school requires the acknowledgement & abstract sections to be included in the table of contents. 

Relatedly, I am required to have the roman numbering for the front matter to start on the Acknowledgements page, rather than on the List of Figures page. 

I see in docs → _main.tex (see below) that the roman page numbers are invisible until ToC, but I can't seem to find a way to unhide them. 

% JEM: Pages are roman numbered from here, though page numbers are invisible until ToC.  This is in
% keeping with most typesetting conventions.
\begin{romanpages}

 

Therefore, the table of contents would be something like this, with corresponding, visible roman numbering on the Acknowledgements and Abstract pages: 

Acknowledgements........................... ii
Abstract........................... iii
List of Tables.............vii
List of Tables.............viii

I've been absolutely loving this package so far, thank you so much for setting it up!

(FYI this is my first time creating an issue, so happy to clarify further as needed). 

Best,

Keana

**Comment by ulyngs** [comment]
Just added options for doing this in 849ab65688db42ca7940009812a1e85be9602459

In **index.Rmd** you can now set these to true, and the acknowledgments and/or abstract will be included in the table of contents.

``` markdown
show-acknowledgements-in-toc: true
...
show-abstract-in-toc: false
```

Based on [this](https://tex.stackexchange.com/questions/25798/how-can-i-add-abstract-and-acknowledgement-pages-into-the-table-of-contents)
