### ISSUE TITLE
Commenting out the "university-logo" in the yaml leads to an error

### ISSUE THREAD

**Issue by zavud** [ulyngs/oxforddown#43]
I do not want to include a logo and therefore I comment out the corresponding line in the yaml as follows:

```
#university-logo: templates/beltcrest.pdf
```

and it leads to the following error:

```
output file: _main.knit.md

! Undefined control sequence.
\HyOrg@maketitle ...e *{\gapbeforecrest } {\crest 
                                                  \par } \vspace *{\gapafter...
l.267 

Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info.
Execution halted
```

How can I solve this? :)

**Comment by ulyngs** [comment]
Thanks for flagging this! I just fixed this with the latest commit, 894715009f43fb2278ded84623742c2484493a47

If you copy the latest version of the repository, you can now comment out the university logo line (or set it to `university-logo: false` and it will exclude the logo as expected. :)
