### ISSUE TITLE
The part before "Why use it?" in the Introduction is now in Japanese as attached.

### ISSUE THREAD

**Issue by kizen777** [ulyngs/oxforddown#44]
The part before "Why use it?" in the Introduction is now in Japanese as attached. 
BTW, Is this the correct way to contact you?
---
#########################################
# options for knitting a single chapter #
#########################################

オックスフォード大学で自分の博士論文を書く際に作成したRMark-down用の論文テンプレート、`oxforddown` [@lyngsOxforddown2019]へようこそ。このテンプレートでは、RMarkdownで書きながら、美しく実績のあるOxThesisLaTeXテンプレートでPDF出力をフォーマットすることができ，かつ，長い間使われてきた美しいOxThesisLaTeXテンプレートでPDF出力をフォーマットすることができます。[my own PhD thesis](https://ulyngs.github.io/phd-thesis/) at the University of Oxford.
   もしあなたがTeXやLaTeXを使ったことがないのであれば*R Markdown*で論文を書くことで、OxThesisテンプレートへのより良いインターフェイスを提供できることを願っています。さらに重要なことは、R Markdownを使うと、論文の中にコードの塊を埋め込むことができ、コピー＆ペーストの手順を避けて、基礎となるデータから直接プロットや表を生成することができるということです。これにより、再現可能な研究を行う習慣が身に付き、研究者としての長期的な利益となり、将来的にあなたの結果を再現したり構築したりしようとする人の助けにもなるのです。
## Why use it? {.unnumbered}
-------Error message------
processing file: 00-introduction.Rmd
output file: 00-introduction.knit.md

! Package inputenc Error: Unicode character オ (U+30AA)
(inputenc)                not set up for use with LaTeX.

Try other LaTeX engines instead (e.g., xelatex) if you are using pdflatex. See https://bookdown.org/yihui/rmarkdown-cookbook/latex-unicode.html
 エラー: LaTeX failed to compile 00-introduction.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See 00-introduction.log for more info.
 追加情報:  警告メッセージ: 
1:  grep("^\\s*$", x) で:   入力文字列 1824 はこのロケールでは不適切です 
2:  grep("^! ", x) で:   入力文字列 1824 はこのロケールでは不適切です 
 実行が停止されました

_Originally posted by @kizen777 in https://github.com/ulyngs/oxforddown/issues/42#issuecomment-1079636011_

**Comment by ulyngs** [comment]
Thanks for this -- I'm closing this issue, as this information should just go in the other issue you already opened :)
