### ISSUE TITLE
Default latex engine doesn't work at times

### ISSUE THREAD

**Issue by pratik-bhandari** [ulyngs/oxforddown#47]
# Specify latex engine

- The default pdflatex engine throws a UTF-8 encoding error
-  Perhaps, add a line to let users select a latex_engine in the index.Rmd file that works?

**Comment by ulyngs** [comment]
R Markdown by default uses `pdflatex`, but this can easily be changed: https://bookdown.org/yihui/rmarkdown/pdf-document.html

As you point out, pdflatex can have some issues with various more complicated unicode characters, which then requires people to set the latex engine to e.g. `xelatex`

Do you know if there would be any unexpected consequences of simply changing `oxforddown`'s default to `xelatex`?

**Comment by pratik-bhandari** [comment]
I work with this additional YAML line in the index.Rmd file: `latex_engine: xelatex` (in line 165) without any problem. But for other projects, sometimes RStudio throws a rendering error related to `tinytex` when the engine is `xelatex`. Not sure why.\
Again, as far as `oxforddown` is concerned, there is no problem with `xelatex`.

**Comment by ulyngs** [comment]
Default latex engine is now `xelatex`: b0a525afa58ae8c7f9d57b3f664491b487c4e851
