### ISSUE TITLE
Changing the order of Abstracts and Acknowledgements

### ISSUE THREAD

**Issue by jefflee1103** [ulyngs/oxforddown#48]
Dear @ulyngs,

First of all, thank you for the fantastic resource.
Is it possible to change the order or Abstracts and Acknowledgements, so that the first (and second) Abstract pages come first?

Many thanks,

Jeff

**Comment by ulyngs** [comment]
Sure, just go to **templates/template.tex** and find this part (should begin around line 375):

```latex
\begin{acknowledgements}
 	$acknowledgements$
\end{acknowledgements}
```

Move this down under the section below it, which inserts the abstracts
