### ISSUE TITLE
Unable to add the style of specific portfolios/templates for chapters

### ISSUE THREAD

**Issue by JoseBSL** [ulyngs/oxforddown#5]
I'm doing a thesis by publications and each chapter is a journal article with different authors and affiliations. I'm trying to add specific portfolios/templates of journal articles for different chapters but this does not work when I build all and just when I knit the independent Rmd files. 

Examples of the templates that I'm using: https://github.com/Pakillo/template

Any idea how can I include the journal style for these different chapters? 

Thanks!

**Comment by ulyngs** [comment]
It is not possible to assign different templates to different chapters.

In the case of a portfolio thesis where some chapters are previously published, you can instead include the individual pages from those papers as PDF in your thesis.

Benjamin Van Doren did this for his thesis - I think this can be done with knitr::include_graphics?

**Comment by bmvandoren** [comment]
Yes, I used knitr::include_graphics to insert PDFs of published papers into my thesis. However, knitr::include_graphics does not appear to support multi-page PDFs, so I first had to split my PDF into multiple files such that each file had only one page. (I also cropped out the margins of the PDF file in Adobe Acrobat.) I then used the following code to insert them. It obviously only works for latex output.

````
```{r, results='asis',echo=F,message=F}
cat('\\newpage')
```

```{r, echo=F, results='asis'}
pages <- list.files(file.path(PATH_TO_DIRECTORY_WITH_PDF_FILES),
                    pattern="FILENAME_PATTERN",full.names = T)

cat(paste0("\\begin{center} \\makebox[\\linewidth][c]{\\includegraphics[width=1.15\\linewidth]{", pages, "}} \\end{center} \\newpage \n"))
```
````

By changing the value multiplying linewidth (currently 1.15), you can make the embedded PDF take up more or less of the width of the page.

**Comment by JoseBSL** [comment]
This seems that will do the work. Thanks!

**Comment by JoseBSL** [comment]
This seems that will do the work. Thanks!

**Comment by ulyngs** [comment]
We've added a new 'customisations and extensions' chapter in the sample materials which addresses this.
