### ISSUE TITLE
sections instead of chapters

### ISSUE THREAD

**Issue by haohua** [ulyngs/oxforddown#51]
Hi Ulrik, 

thank you so much for putting together such clean and well-organized templates. 

I want to build a single paper based on your oxforddown. 
Can I convert the chapters into sections, so that there will be no page break for each section?

Also, can I change the chapter title position from the "Top Right" corner with a big number, to the "Top Left" corner? 

thank you 
andy

**Comment by ulyngs** [comment]
Hi Andy,

first question: yes, you can convert chapters to sections using the appropriate pandoc commandline argument in **index.Rmd** (see [this StackOverflow](https://stackoverflow.com/questions/49198680/bookdown-converting-chapters-to-sections)): --top-level-division=section

In other words, go to **index.Rmd**, then change the `pandoc_args` variable to this:

```
pandoc_args: ["--lua-filter=scripts_and_filters/colour_and_highlight.lua", "--top-level-division=section"]
```

**Comment by ulyngs** [comment]
I am going to move your other question into its own issue, #52
