### ISSUE TITLE
Switching between different languages

### ISSUE THREAD

**Issue by MalteHueckstaedt** [ulyngs/oxforddown#56]
Hi, 

Is there a way to switch between English and German in different chapters? My main concern is that table and figure labels are changed accordingly. 

I would be very grateful for any tips :)

Thank you very much,
Malte

**Comment by MalteHueckstaedt** [comment]
I think I found the answer myself: 
It was sufficient for me to insert `\selectlanguage{british}` under the YAML :)

**Comment by Dilan-Manosalvas** [comment]
Hi,
Where exactly do I write the code for YAML?

**Comment by MalteHueckstaedt** [comment]
Hi @Dilan-Manosalvas, 

usually you write the YAML at the beginning of your R markdown file. E.g. like this: 

```
---
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
    latex_engine: xelatex
  bookdown::html_document2: default
  bookdown::word_document2: default
documentclass: book'
#bibliography: [bibliography/references.bib, bibliography/additional-references.bib]
---
\selectlanguage{british}

```
