### ISSUE TITLE
Incorrect section header at top of page in references

### ISSUE THREAD

**Issue by JanaMuschinski** [ulyngs/oxforddown#63]
I found this issue in my own doc and tested in the most current version on the repository by adding in a bunch of citations to confirm it's an issue there as well. 

When the references go across more than one page, the following pages have the faint section header of the previous section ("B. Second Appendix for Fun" in the case of the template) at the top where it should say "References". This wasn't an issue in an earlier version from March, but I can't get that version of the template to work because I was having problems with biblatex and it compiles better with pandoc citations using the newest version. Issue persists if you compile with biblatex citation package. 

Would love to include section headers if this can be sorted, but otherwise I'll omit them :)

**Comment by ulyngs** [comment]
Ah interesting -- not entirely sure I understand correctly, can you add a few screenshots and/or provide a minimal reproducible example?

**Comment by JanaMuschinski** [comment]
Here you go!

From my own document - see header highlighted; it's showing the name of my last appendix, rather than "References"
![image](https://user-images.githubusercontent.com/63369324/189522697-625435b6-fd5d-4bd6-9489-95ce0610dac8.png)


From the template, but with added references so it extends past one page:
![image](https://user-images.githubusercontent.com/63369324/189522778-be6f4d3a-63f2-48a2-9ecc-8b70fb548b6d.png)


For a reproducible example - if you add further citations to your Oxforddown template so that the references/work cited page extends beyond one page in length you'll be able to see it on any pages after the first reference page.

**Comment by JanaMuschinski** [comment]
Compared to a previous document made using the template when downloaded in March: 
![image](https://user-images.githubusercontent.com/63369324/189523036-542a2a2a-41bf-46f0-a831-986e31c311ee.png)

**Comment by ulyngs** [comment]
Fixed!

(turns out I just needed to add 

```latex
% set the section header to the references heading
\markboth{$params.referenceHeading$}{}
```

to the end of the oxforddown latex template.

Can you check if the fix is working?

**Comment by JanaMuschinski** [comment]
Amazing! Thank you so much. I'll take a look at the changes you've made, test them out and let you know if I'm still having trouble.
