### ISSUE TITLE
polish letters

### ISSUE THREAD

**Issue by agamat** [ulyngs/oxforddown#67]
Hi,

I would like to use polish letters, but they are not printed in pdf (1 exception is printed : letter "ó")

Is there any possibility to fix it?

thanks and regards

**Comment by ulyngs** [comment]
Try adding `\usepackage{polski}` to **templates/template.tex**, for example under line 33 where it says "%%%%% ADDING LATEX PACKAGES"

If that doesn't do the trick on its own, google "latex polish letters" and see what packages are required to get special characters in polish to show up!

**Comment by agamat** [comment]
thank you, 
\usepackage{polski}  does not help
I tried few other options.. not there yet .. tbc...

**Comment by ulyngs** [comment]
Let me know if you find a solution!

**Comment by ulyngs** [comment]
@agamat can you give me a minimally reproducible example?

**Comment by agamat** [comment]
hi, thank you for being interested :), sorry for not coming back earlier, I already wrote the thesis in pl (not using oxforddown), now I am writing in eng with oxforddown and have another question/issue (I start new one)
