### ISSUE TITLE
"Render" output

### ISSUE THREAD

**Issue by agamat** [ulyngs/oxforddown#68]
Hi,
When I knit brand new oxforddown (not a single change made) in Rstudio, I get under "Render" tab the following message:

Warning: Package inputenc Warning: inputenc package ignored with utf8 based engines.
Warning: Package fancyhdr Warning: \fancyhead's `E' option without twoside option is useless on input line 179.
Warning: LaTeX Warning: Command \@parboxrestore  has changed.
Warning:                Check if current package is valid.
Warning: Package fvextra Warning: csquotes should be loaded after fvextra, to avoid a warning from the lineno package on input line 37.

Output created: docs/_main.pdf
Warning messages:
1: In get_engine(options$engine) :
  Unknown language engine 'yaml' (must be registered via knit_engines$set()).
2: In get_engine(options$engine) :
  Unknown language engine 'yaml' (must be registered via knit_engines$set()).
3: In get_engine(options$engine) :
  Unknown language engine 'yaml' (must be registered via knit_engines$set()).

Would  you have similar output?  (I compared with for example ... thesisdown - no  issue there)

**Comment by ulyngs** [comment]
Yup, those warnings are not to be worried about --- I should probably see if there's a way to get rid of them!

Does your PDF output look as expected?

**Comment by ulyngs** [comment]
Thanks for flagging this; I finally got around to chasing down the origin of the warning messages and have corrected them all -- except for the one related to `fancyhead` as this one just raises your attention to the fact that the appearance of headers depend on whether you've set a twoside binding option or not

Fixed w/ 5448b6d3d5b6eefdb7dd106ee7efa4e9b2b4cff2, 2c3f6021f057c37132900224eeb5f5f0f34c7b4c, and f773fb37626eaec82cca566d70160abec986c5c0
