### ISSUE TITLE
Figure caption placement

### ISSUE THREAD

**Issue by ogsteele** [ulyngs/oxforddown#71]
I've recently come across an issue relating to the positioning of figure captions when the image is full screen. Please see the below example and attached code used to generate the issue. In the below example stops on the page (over the watermark/page number) however I believe the default behaviour is to simply keep printing it, and have the text cut off by the end of the page. 

Are you aware of a way in which to physically seperate the figure from the caption, yet still have them associated? Or perhaps half of the caption at the bottom of that page, and the rest at the top of the next page? 

Failing this, I suspect the easiest solution might simply be to use figures with fewer panels in them - but thought i'd ask in case you knew an easy way to do this / this was useful for anyone else. 

```
{r NaKrescuefig, fig.cap ="\\textbf{APOE4 impairs membrane excitability, yet not individual action potential properties} Organotypic hippocampal brain slices were prepared from APOE TR mice pups at DIV6-8 and cultured to DIV21 before investigation of actoon potential properties in a current step protocol. Individual action potential properties were unaffected by APOE genotype. However, a significant APOE4 dependent impairment to membrane excitability was noted when monitoring number of action potentials as a function of current injected.", fig.scap="APOE4 impairs membrane excitability, yet not individual action potential properties ", out.width="100%", echo=FALSE}
knitr::include_graphics("./figures/intrinsic/fig6_NaKrestoration.png")
```

![image](https://user-images.githubusercontent.com/69857520/198825244-4e576e1c-6ead-4a89-8fd2-24740cb09094.png)

PS. Absolutely loving your work, hugely useful in writing my own thesis. Thank you!!

**Comment by ulyngs** [comment]
Have a look here: https://tex.stackexchange.com/questions/53315/how-to-put-large-figure-caption-on-separate-page-from-the-figure

Think there's a LaTeX package to make a figure caption overflow to the next page. Personally my aesthetical preference would be to not have a figure caption overflow, but instead reduce the figure size and/or make the caption shorter :)

**Comment by ogsteele** [comment]
I don't often soo caption overflow done, so suspect you're right. Reduced figure size it is! 

Thanks for the link, useful to know it is still possible within the framework of the thesis. Thanks for taking the time to answer too!
