### ISSUE TITLE
Linespacing varies amongst pages

### ISSUE THREAD

**Issue by alexdank** [ulyngs/oxforddown#73]
Hi,

I encounter a problem when knitting documents from the index.rmd file.

Here’s the problem:
When knitting the _main thesis document, line spacing seems to be variable at some locations (see examples below):

 
![image](https://user-images.githubusercontent.com/38498565/204878814-a18d6818-ca32-4a12-a2a7-f8c9b234d322.png)

![image](https://user-images.githubusercontent.com/38498565/204878876-3893433c-0ddf-40bc-afa2-59e34195d67e.png)

 
 
 
I’ve got the feeling it has something to do with the placement of figures on the pages before or after the error, but I am not certain.
Interestingly, when I knit the document as single chapter, the text does not behave like this.
Do you have any clue what could be the issue? It would be of great help!

Below my sessioninfo

```
`> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
```

    `

**Comment by alexdank** [comment]
The problem can be more or less reduced by playing with the figure sizes, placements and forcing \newpage on some segments, but still varying linetypes appear (only differences between spacing is reduced now) and this process seems to be 'trial and error'.

**Comment by mtthwborg** [comment]
I have this issue too, but it occurs both with the full thesis and a single chapter. Similarly to the OP, it also seems to occur between figures on different pages, where the text seems to increase in spacing to pad out the remaining page.

**Comment by ulyngs** [comment]
Can you provide a minimally reproducible example? And can you also see whether this occurs with the same content when outputting to an ordinary PDF file? 

(I suspect that what you are describing is normal behaviour by LaTeX?)

**Comment by alexdank** [comment]
Okay, I did some extensive googling and found out it  is a result of setting the \setlength{\parskip}{ length} argument in the template.tex file. (see https://tex.stackexchange.com/questions/108978/variable-white-space-between-paragraphs).
Hence, indeed it is normal latex behaviour, as latex automatically adjusts the spaces between each line in the paragraphs to fit the page, and this is influenced by for instance figure placements. 
Anyway, for me changing the values to the following 'solved' my problem -- The spacing differences were minimalized.

% UL: You can set the general paragraph spacing here - I've set it to 2pt (was 0) so
% it's less claustrophobic
\setlength{\parskip}{0.1pt plus 0.1pt}

**Comment by ulyngs** [comment]
@alexdank thanks for looking into this! Do you think there is any action for me here? That is, do you think I should change the `oxforddown` default setting to your solution?

**Comment by alexdank** [comment]
@ulyngs Considering I was not the only one with this 'issue' it might be advisable to reduce the default settings for paragraph spacing to avoid further 'issues' with other users. I think it is especially relevant for people that (like me) have many figures in one chapter, increasing the 'risk' of abnormal line spacing due to the parskip length settings.

**Comment by ulyngs** [comment]
How about I reduce the default setting, and make the paragraph spacing controllable from **index.Rmd** along with an explanation of how to read the spacing settings? 

``` latex
% spacing: how to read {12pt plus 4pt minus 2pt}
%           12pt is what we would like the spacing to be
%           plus 4pt means that TeX can stretch it by at most 4pt
%           minus 2pt means that TeX can shrink it by at most 2pt
```
