### ISSUE TITLE
if show-abstract-in-toc: true, Abstract TOC hyperlink is to Acknowledgements

### ISSUE THREAD

**Issue by mtthwborg** [ulyngs/oxforddown#75]
If show-abstract-in-toc in _index is made to be true, the Abstract is added to the TOC (table of contents). However, the hyperlink for the abstract moves to Acknowledgements instead. Acknowledgements is not included in TOC but is the page before the Abstract.

All I did was change show-abstract-in-toc in _index to true (default is false); nothing else was changed in oxforddown. However, I tested adding \phantomsection to template.tex, which did fix the hyperlink [(source)](https://tex.stackexchange.com/questions/44088/when-do-i-need-to-invoke-phantomsection). Perhaps this could be incorporated into the template?

```latex
%%%%% ABSTRACT
$if(abstract)$

$if(show-abstract-in-toc)$
\phantomsection % NEW INSERTION, or \providecommand\phantomsection{}
\addcontentsline{toc}{chapter}{$if(abstract-heading)$$abstract-heading$$else$Abstract$endif$}
\renewcommand{\numberstyleabstract}{plain}
$endif$

\renewcommand{\abstracttitle}{$if(abstract-heading)$$abstract-heading$$else$Abstract$endif$}
\begin{abstract}
	$abstract$
\end{abstract}

$endif$
```

On a somewhat related note from adding sections before the main chapters (such as a list of keywords and presentations), I needed to use \phantomsection for each section, as well as \newpage before them. This solved the links. The roman numerals in the table of contents for the earlier sections did not align with the actual roman numeral page numbers, and the last section did not show despite being added to the ToC. These issues do not affect the unchanged oxforddown, but may be issues inherent to the template possibly for the same reasons that the abstract link is misaligned.

**Comment by ulyngs** [comment]
Fixed w/ dc80bb5e5df97a8b40326083107ec7a390378284  -- thanks for flagging this!
