### ISSUE TITLE
Cannot find font information and ways to change it

### ISSUE THREAD

**Issue by alexdank** [ulyngs/oxforddown#76]
Hi Ulyngs,

The title pretty much explains it; I've tried finding the font settings in various templates but have trouble locating them.
Could you indicate where to find it and how to change it?
Would be of great help!

**Comment by ulyngs** [comment]
See [this guidance] on Overleaf.

For example, add this to **templates/template.tex**, before `\begin{document}`

```latex
\usepackage[T1]{fontenc}
\usepackage{tgbonum}
```

And you get this:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/23137032/230847285-8f56ffe3-b079-42e1-b2f6-6cf77368f2b3.png">
