### ISSUE TITLE
remove the page breaks for each chapter

### ISSUE THREAD

**Issue by haohua** [ulyngs/oxforddown#77]
Thank you so much for putting together the package. 

I need to remove the page breaks for each new chapter. So it is more like traditional paper, not the book. Do you know if there is any option i can change in your package to remove the page breaks?

thank you

**Comment by ulyngs** [comment]
See [this discussion on Stackoverflow](https://tex.stackexchange.com/questions/24066/start-new-chapter-on-same-page):

To start a *single* chapter on the same page as where the previous chapter ends, if there is space:
In the **.Rmd** file for a chapter, replace `# The title of your chapter` with

```latex
\begingroup
\let\clearpage\relax
\chapter{The title of your chapter}
\endgroup
```

To *always* start chapters on the same page (Not recommended -- it will apply to *all* the chapter-level headings, including the front matter), add this to **templates/template.tex**:

```latex
% chapters
\usepackage{etoolbox}
\makeatletter
\patchcmd{\chapter}{\if@openright\cleardoublepage\else\clearpage\fi}{}{}{}
\makeatother
```
