### ISSUE TITLE
Modify chapter numbering format

### ISSUE THREAD

**Issue by gsarti** [ulyngs/oxforddown#8]
I am using an adapted version of this project for my master thesis. 

I tried to fiddle with the latex templates but I didn't manage to change the huge grey numbers that appear as defaults at the beginning  of each chapter. Moreover, I wasn't able to identify the package responsible for their rendering.

I tried the `titlesec` approach, as suggested by many on StackOverflow, but it doesn't seem to work. Can you provide me with a minimal example that makes the format of chapter names editable?

Thank you in advance for your time!

**Comment by ulyngs** [comment]
I just looked into this, you can change it easily yourself by adding something like this to **template.tex** after `\usepackage{titlesec}`:

(I took this example [from here](https://tex.stackexchange.com/questions/94729/how-to-customize-chapter-heading-style))

```latex
\titleformat{\chapter}[display]
  { \normalsize \huge  \color{black}}
  {\flushright \normalsize \color{red} \MakeUppercase { \chaptertitlename } \hspace{1 ex} { \fontsize{60}{60}\selectfont \color{red} \sffamily  \thechapter }} {10 pt}{\huge}
```

This will override `oxforddown`'s default chapter style and give you this:

<img width="824" alt="Screenshot 2021-05-24 at 09 48 47" src="https://user-images.githubusercontent.com/23137032/119322132-4339f780-bc75-11eb-81d0-16e81004f44a.png">

**Comment by gsarti** [comment]
Thank you for your answer and for the incredible work! I solved the problem during last year and I managed to publish my MSc thesis last December! :smile: 

If you'd like to link to it in the examples section, you can find it here: [https://gsarti.com/thesis/introduction.html](https://gsarti.com/thesis/introduction.html)

The edited source files are on Github, if you want to take a look: [https://github.com/gsarti/masters-thesis](https://github.com/gsarti/masters-thesis).

**Comment by ulyngs** [comment]
added to the readme, thanks Gabriele!

**Comment by ulyngs** [comment]
And the answer provided in #52 for how to move the chapter title to the left: Add the following to template.tex after \usepackage{titlesec}:

```latex
\titleformat{\chapter}[display]
  { }
  {\flushleft { \fontsize{60}{60}\selectfont  \thechapter }} 
  {10 pt} % spacing before chapter title
  { \huge } % command after chapter number (this will make the chapter title size huge) 
```

This will give you

<img width="654" alt="image" src="https://user-images.githubusercontent.com/23137032/169689182-dfd63816-5917-444c-996b-e1fa3584aaaf.png">
