### ISSUE TITLE
Missing Book Title in Bibliography Citations (citing book section)

### ISSUE THREAD

**Issue by Alathen** [ulyngs/oxforddown#85]
### Issue
I am currently utilizing an R Markdown template for my documents and find it very efficient. However, I've noticed a recurring issue with the bibliography when I knit the document. Specifically, when citing a book section, the title of the book is missing in the reference list.

**Exemple Refrence:**
Eichenberger, Steven, and Frédéric Varone. 2020. “Interest Groups and Direct
Democracy.” In, edited by Phil Harris, Alberto Bitonti, Craig S. Fleisher, and
Anne Skorkjær Binderkrantz, 1–8. Cham: Springer International Publishing.
https://doi.org/10.1007/978-3-030-13895-0_86-1.

**Missing Information:**
After the "In" in the reference, the title of the book should be included: The Palgrave Encyclopedia of Interest Groups, Lobbying and Public Affairs.

**Comment by ulyngs** [comment]
I can't recreate this issue -- I get this in the references
<img width="471" alt="image" src="https://github.com/user-attachments/assets/ccc52966-1159-4032-ac6f-8b796be808f9">
